name: Build Spigot for Akashic Server
# By Myth, created for Akashic Server


on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    
    - uses: actions/checkout@v2

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    
    - name: Build Spigot
      env: 
        REV: ${{ secrets.REV }}
      run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && java -jar BuildTools.jar --rev ${REV}

    - name: Upload Spigot
      uses: actions/upload-artifact@v2
      with:
        name: Spigot.jar
        path: ./spigot*.jar
